name: track-image-processing
channels:
- defaults
- conda-forge
- franklab
- edeno
dependencies:
- python >=3.8,<3.11
- numpy
- scipy
- jax >=0.4.12
- jaxlib >=0.4.6
- flax
- optax
- scikit-image
- pandas
- networkx
- xarray
- scikit-learn
- patsy
- tqdm
- track_linearization
- matplotlib
- seaborn
- ipython
- black
- pytest
- pytest-cov
- pip
- pip:
  - scikit-video